spring:
  application:
    name: helios
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

gemini:
  api-key: ${GEMINI_API_KEY:AIzaSyCn1Oz6VMCkPK81amlF93F69JOInPorURs}
  model-name: ${GEMINI_MODEL_NAME:gemini-2.0-flash-exp}
